### ISSUE TITLE
Glow_TTS Inference_Example.ipynb issues on Linux machine

### ISSUE THREAD

**Issue by patdflynn** [CODEJIN/Glow_TTS#6]
Hi,

I'd like to get Inference_Example.ipynb working on a Linux server using the pretrained LJ + VCTK speaker embedding checkpoint. If it's any easier I'd like to get it working in look up table mode and eventually train for GE2E speaker embeddings. This is the process I've followed so far:

1. Import a pretrained checkpoint and hyper_parameters.yaml (in my case I'm using mulispeaker LJ + VCTK)
2. Import the LJ and VCTK datasets under "\Pattern\ENG\LJSpeech" and \Pattern\ENG\VCTK"
3. Modify paths in hyper_paramiters.yaml
4. Run Pattern_Generator.py on with those two datasets
5. We encountered several errors related to the directory paths, pickle file, and mvSound function (it was refered to sound in the hyper parameter yaml checkpoint file. It worked after we renamed it to Sound)
6. We made a try/except for line 103 to work since we had were no eval patterns
7. Setup the cython file for monotonic alignment
8. Ran into an error in the final cell (see images)

![1](https://user-images.githubusercontent.com/44388720/100306884-6e67b680-2f72-11eb-9291-ca7246a057fb.png)
![2](https://user-images.githubusercontent.com/44388720/100306887-70ca1080-2f72-11eb-9574-912dcc1b4fc1.png)
![3](https://user-images.githubusercontent.com/44388720/100306891-73c50100-2f72-11eb-8530-55e92d74f933.PNG)

Also is the purpose of the pattern generator file to make it easy to transfer between machines?

Thank you!

**Comment by CODEJIN** [comment]
Hi, @patdflynn

Sorry for late reply.

1. This problem occurs when the `numpy` version is downgraded by some reasons. Would you like to check the `numpy` version in your current environment? When I installed another module, the numpy version was forcibly downgraded to 1.16, causing the problem. My current `numpy` version is 1.19.
If for any reason it is difficult to change the current `numpy` version, try modifying line 26 to read:
```
[np.pad(token, [0, max_Token_Length-token.shape[0]], mode='constant', constant_values= token_Dict['<E>']) for token in tokens],
```
The `mode` parameter is assigned 'constant' by default since 1.17, so lower versions than 1.17 will cause the problem you are facing.

2. The main reason is for file managing. Many open sources convert only to npy and use it, but in that case, there is an inconvenience of having to manage the text file separately. In addition, some models such as vocoder and voice conversion may require additional information such as wav form, pitch, or speaker id. Separately managing additional files for that information increases resources for management.
The part you talked about is not wrong either. However, the pickled files may be larger than the originals, so it may be faster to do preprocessing again on the new machine. And, this approach also has its drawbacks. Models have to read information they don't need. If you don't use cache, model will have the same problem with every epoch. This method is just a way I'm comfortable with it, so I think you can edit the dataset in the form you want when you use it.

Thanks,

Heejo

**Comment by patdflynn** [comment]
Thank you!
